/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

#define RCC_BASE_ADDR         0x40023800UL
#define RCC_CFGR_REG_OFFSET   0x08UL
#define RCC_CFGR_REG_ADDR     (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
#define RCC_CR_REG_OFFSET     0x00UL
#define RCC_CR_REG_ADDR       (RCC_BASE_ADDR + RCC_CR_REG_OFFSET)
#define GPIOA_BASE_ADDR       0x40020000UL


int main(void)
{

	uint32_t *pRccCrReg    = (uint32_t *) RCC_CR_REG_ADDR;
	//1) Configure the RCC_CR HSEBYP bitfields to select HSE as bypass.
	*pRccCrReg &= ~(1 << 18);  //clear HSEBYP
	*pRccCrReg |=  (1 << 18);  //set   HSEBYP

	*pRccCrReg &= ~(1 << 16);  //clear HSEON
	*pRccCrReg |=  (1 << 16);  //set   HSEON

	while (!(*pRccCrReg & (1 << 17))) ;  //wait to clock stabilize
	
	
	uint32_t *pRccCfgrReg  = (uint32_t *) RCC_CFGR_REG_ADDR;
	//1) Configure the RCC_CFGR MC01 bitfields to select HSE as clock source.
	*pRccCfgrReg |=  (0x1 << 0);

	*pRccCfgrReg &= ~(0x3 << 21);
	*pRccCfgrReg |=  (0x1 << 22);
	
	    //Configure MCO1 prescaler
	*pRccCfgrReg |=  (1 << 25);
	*pRccCfgrReg |=  (1 << 26);

	//2) Configure PA8 to Alternate Function AF0 to act as MCO1 signal
	//  a) Enable the GPIOA peripheral
	uint32_t *pRCCAbh1Enr = (uint32_t *) (RCC_BASE_ADDR + 0x30);
	*pRCCAbh1Enr |= (1 << 0); //enable GPIOA peripheral clock.

	//  b) configure the mode of GPIOA pin 8 - PA8 - as alternate function AF0
	uint32_t *pGPIOAModeReg = (uint32_t *) (GPIOA_BASE_ADDR + 0x00);
	*pGPIOAModeReg &= ~(0x03 << 16); //clear
	*pGPIOAModeReg |=  (0x02 << 16); //set

	//  c) configure the alternate function register to set the mode 0 at PA8
	uint32_t *pGPIOAAltFuncHighReg = (uint32_t *) (GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFuncHighReg &= ~( 0x0F << 0);

	for(;;);
}
