/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

#define RCC_BASE_ADDR         0x40023800UL
#define RCC_CFGR_REG_OFFSET   0x08UL
#define RCC_CFGR_REG_ADDR     (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
#define GPIOA_BASE_ADDR       0x40020000UL


int main(void)
{
	uint32_t *pRccCfgrReg  = (uint32_t *) RCC_CFGR_REG_ADDR;

	//1) Configure the RCC_CFGR MC01 bitfields to select HSI as clock source.
	*pRccCfgrReg &= ~(0x3 << 21);
	    //Configure MCO1 prescaler
	*pRccCfgrReg |=  (1 << 25);
	*pRccCfgrReg |=  (1 << 26);

	//2) Configure PA8 to Alternate Function AF0 to act as MCO1 signal
	//  a) Enable the GPIOA peripheral
	uint32_t *pRCCAbh1Enr = (uint32_t *) (RCC_BASE_ADDR + 0x30);
	*pRCCAbh1Enr |= (1 << 0); //enable GPIOA peripheral clock.

	//  b) configure the mode of GPIOA pin 8 - PA8 - as alternate function AF0
	uint32_t *pGPIOAModeReg = (uint32_t *) (GPIOA_BASE_ADDR + 0x00);
	*pGPIOAModeReg &= ~(0x03 << 16); //clear
	*pGPIOAModeReg |=  (0x02 << 16); //set

	//  c) configure the alternate function register to set the mode 0 at PA8
	uint32_t *pGPIOAAltFuncHighReg = (uint32_t *) (GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFuncHighReg &= ~( 0x0F << 0);


	for(;;);
}
